
name: Publish Library in NPM
on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check the project
      uses: actions/setup-node@v1
      with:
        node-version: '14.19.1'

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Test
      run: npm run test:coverage

    - name: Publish package
      run: npm publish --ignore-scripts --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}